name: Cleanup proxies

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: false

on: 
  workflow_dispatch:

jobs:
  Main-Job:
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: cleanup
        id: cleanup
        uses: ./cleanup
        with:
          oci-compartment-name: ${{ secrets.OCI_COMPARTMENT_NAME }}
          max-duration-secs: 0
